varDictionnaries:
  - name: "TrueMode"
    dictionary:
      - { value: 0, title: "QE", color: 855 } # Blue
      - { value: 1, title: "RES", color: 800 } # Orange
      - { value: 2, title: "DIS", color: 842 } # Greenish
      - { value: 3, title: "COH", color: 866 } # Sky Blue
      - { value: 10, title: "MEC", color: 805 } # Vermillion
      - { value: -1, title: "Cosmic", color: 617 } # Purplish

histogramsDefinition:
  - varToPlot: "TrueHadronicOpeningAngle"
    splitVars: ["", "TrueMode"]
    useSampleBinning: true
    xTitle: "True Cosine of Proton Pair Opening Angle"
    yTitle: "#frac{d #sigma}{d cos(#theta_{p,p})} #frac{cm^{2}}{Ar}"

  - varToPlot: "TrueMuonHadronAngle"
    splitVars: ["", "TrueMode"]
    useSampleBinning: true
    xTitle: "True Cosine of Muon-Proton Pair Opening Angle"
    yTitle: "#frac{d #sigma}{d cos(#theta_{#mu,pp})} #frac{cm^{2}}{Ar}"

  - varToPlot: "TrueDeltaPT"
    splitVars: ["", "TrueMode"]
    useSampleBinning: true
    xTitle: "True #delta p_{#text{T}} (GeV/c)"
    yTitle: "#frac{d #sigma}{d #delta p_{#text{T}}} #frac{cm^{2}}{(GeV/c)Ar}"

  - varToPlot: "TrueDeltaPTT"
    splitVars: ["", "TrueMode"]
    useSampleBinning: true
    xTitle: "True #delta p_{#text{TT}} (GeV/c)"
    yTitle: "#frac{d #sigma}{d #delta p_{#text{TT}}} #frac{cm^{2}}{(GeV/c)Ar}"

  - varToPlot: "TrueDeltaAlphaT"
    splitVars: ["", "TrueMode"]
    useSampleBinning: true
    xTitle: "True #delta #alpha_{#text{T}}"
    yTitle: "#frac{d #sigma}{d #delta #alpha_{#text{T}}} #frac{cm^{2}}{Ar}"

  - varToPlot: "TrueDeltaPhiT"
    splitVars: ["", "TrueMode"]
    useSampleBinning: true
    xTitle: "True #delta #phi_{#text{T}}"
    yTitle: "#frac{d #sigma}{d #delta #phi_{#text{T}}} #frac{cm^{2}}{Ar}"

canvasParameters:
  height: 700
  width: 700
  nbXplots: 1
  nbYplots: 1

