varDictionnaries:
  - name: "TrueMode"
    dictionary:
      - { value: 0, title: "QE", color: 855 } # Blue
      - { value: 1, title: "RES", color: 800 } # Orange
      - { value: 2, title: "DIS", color: 842 } # Greenish
      - { value: 3, title: "COH", color: 866 } # Sky Blue
      - { value: 10, title: "MEC", color: 805 } # Vermillion
      - { value: -1, title: "Cosmic", color: 617 } # Purplish

histogramsDefinition:
  - varToPlot: "TrueDeltaAlphaT"
    splitVars: ["", "TrueMode"]
    useSampleBinning: true
    xTitle: "True #delta #alpha_{#text{T}}"
    yTitle: "#frac{d #sigma}{d #delta #alpha_{#text{T}}} #frac{cm^{2}}{Ar}"

canvasParameters:
  height: 700
  width: 700
  nbXplots: 1
  nbYplots: 1

